longo/urls.py
from django.conf.urls import url
from django.contrib import admin
from lbgo.views import Index, AddArticle, HashTagCloud

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Index.as_view(), name='Main'),
    url(r'^index/$', Index.as_view(), name='Main'),  # main page diplay title + url ,order by pub_date descendent
    url(r'^post/', AddArticle.as_view(), name='Commit'), # commit new article
]

lbgo/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Article(models.Model):
    """
    Article model
    """
    title = models.CharField(max_length=90)
    pub_date = models.DateTimeField(auto_now_add=True)
    url = models.URLField()
    context = models.TextField(max_length=300)
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.title


class HashTag(models.Model):
    """
    HashTah model
    """
    name = models.CharField(max_length=64, unique=True)
    article = models.ManyToManyField(Article)

    def __unicode__(self):
        return self.name

lbgo/forms.py
from django import forms


class ArticleForm(forms.Form):
    title = forms.CharField(label='Article Title', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'type keyword, then click search'}), required=True)
    url = forms.URLField(label='Article Url', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'https://www.google.com'}), required=True)
    content = forms.CharField(label='Article Content', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'abstract...'}), required=True)
    tag = forms.CharField(label='Tags', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'eg: Python,Django,Scala'}), max_length=100)


class SearchForm(forms.Form):
    query = forms.CharField(label='Enter a keyword to search for', widget=forms.TextInput(attrs={'size': 32, 'class': 'form-control'}))

lbgo/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import View
from models import Article, HashTag
from forms import ArticleForm, SearchForm
from api import Spider

# Create your views here.


class Index(View):
    def get(self, request):
        articles = Article.objects.order_by("-pub_date")
        return render(request, 'main.html', {'articles': articles})

    def post(self, request):
        return HttpResponse('Hi, <b>kalimodo</b>, welcome you here!!!')


class AddArticle(View):
    """
    Tweet Post form available on page /post/ URL
    """
    def get(self, request):
        params = dict()
        articles = Article.objects.all()

        # form widgets
        form = ArticleForm()
        params["form"] = form

        return render(request, 'post.html', params)

    def post(self, request):
        form = ArticleForm(request.POST)
        if form.is_valid():

            # get web abstract
            # spid = Spider()
            # data = spid.get_content(form.cleaned_data['url'])

            # save into  article
            art = Article(url=form.cleaned_data['url'],
                          title=form.cleaned_data['title'],
                          context=form.cleaned_data['content'])
            art.save()

            # save into tag, multiple items
            tags = form.cleaned_data['tag']
            tag = tags.split(',')
            while '' in tag:
                tag.remove('') # delete null
            if len(tag) == 0:
                tag = ['python'] # default
            for t in tag:
                hashtag, created = HashTag.objects.get_or_create(name=t)
                hashtag.article.add(art)

            # save into hashtag
            words = form.cleaned_data['tag'].split(",")
            for word in words:
                # at least one keyword
                if len(word) >= 1:
                    hashtag, created = HashTag.objects.get_or_create(name=word[1:])
                    hashtag.article.add(art)
            return HttpResponseRedirect('/index/')


class HashTagCloud(View):
    """
    Hash Tag page reachable from /hashtag/<hashtag> URL
    """

    def get(self, request, hashtag):
        params = dict()
        hashtag = HashTag.objects.get(name=hashtag)
        params["tweets"] = hashtag.tweet
        return render(request, 'hashtag.html', params)

templates/base.html
{% load staticfiles %}
<html>
<head>
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
</head>

<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <a class="navbar-brand" href="#">My Articles List</a>
    <p class="navbar-text navbar-right">User Profile Page</p>
</nav>

<div class="container">

    {% block content %}
    <br>
    <br>
    <h1 class="text-info">HELLO {{ name }}!</h1>
    {% endblock %}

</div>
<br>
<br>
<br>
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
    <p class="navbar-text navbar-right">Footer</p>
</nav>


<script src="{% static 'bootstrap/js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/hashtag.html
{% extends "base.html" %}
{% block content %}
    <div class="row clearfix">
        <br>
        <br>
        <br>
        <div class="col-md-12 column">
            {% for tweet in tweets.all %}
            <div class="well">
                <span>{{ tweet.text }}</span>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/main.html
{% extends "base.html" %}
{% block content %}
    <div class="row clearfix">
        <br>
        <br>
        <br>
        <div class="col-md-12 column">
            {% for article in articles %}
            <div class="well">
                <h4 class="text-info">{{ article.title }}</h4>
                <a href="{{ article.url }}">{{ article.url }}</a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/post.html
{% extends "base.html" %}
{% block content %}
    <div class="row clearfix">
        <br>
        <br>
        <br>
        <div class="col-md-12 column">
            <form class="form-horizontal" role="form" method="post" action="/post/">{% csrf_token %}
              <div class="form-group">
                <label for="id_title" class="col-sm-2 control-label">Title</label>
                <div class="col-sm-10">
                    {{ form.title.errors }}
                    {{ form.title }}
                </div>
              </div>
              <div class="form-group">
                <label for="id_url" class="col-sm-2 control-label">Url</label>
                <div class="col-sm-10">
                    {{ form.url.errors }}
                    {{ form.url }}
                </div>
              </div>
              <div class="form-group">
                <label for="id_content" class="col-sm-2 control-label">Url</label>
                <div class="col-sm-10">
                    {{ form.content.errors }}
                    {{ form.content }}
                </div>
              </div>
              <div class="form-group">
                <label for="id_tag" class="col-sm-2 control-label">Tags</label>
                <div class="col-sm-10">
                    {{ form.tag.errors }}
                    {{ form.tag }}
                </div>
              </div>
              <!--<div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox">is_active
                    </label>
                  </div>
                </div>
              </div>-->
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-default">post</button>
                </div>
              </div>
            </form>
        </div>
        <!--<h3>&nbsp;</h3>
        <div class="col-md-12 column">
            {% for article in params %}
            <div class="well">
                <h3 class="text-info">{{ article.title }}</h3>
                <a href="{{ article.url }}">{{ article.url }}</a>
            </div>
            {% endfor %}
        </div>-->
    </div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block content %}
    <div class="row clearfix">
        <br>
        <br>
        <br>
        <div class="col-md-12 column">
            <form method="post" action="post/">{% csrf_token %}
                <div class="col-md-8 col-md-offset-2 fieldWrapper">
                    {{ form.url.errors }}
                    {{ form.url }}
                </div>
                <div class="col-md-8 col-md-offset-2 fieldWrapper">
                    {{ form.tag.errors }}
                    {{ form.tag }}
                </div>
                <div>
                    <input type="submit" value="post">
                </div>
            </form>
        </div>
        <h3>&nbsp;</h3>
        <div class="col-md-12 column">
            {% for article in articles %}
            <div class="well">
                <h3 class="text-info">{{ article.title }}</h3>
                <a href="{{ article.url }}">{{ article.url }}</a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}